[versions]
kotlin = "1.6.21"
android-plugin = "7.4.2"
app-compat = "1.4.1"
core-ktx = "1.8.0"
fragment-ktx = "1.4.1"
viewpager2 = "1.0.0"
constraintlayout = "2.1.4"
recyclerview = "1.2.1"
coordinatorlayout = "1.2.0"
lifecycle-extensions = "2.2.0"
navigaton = "2.4.2"
material = "1.6.1"
lottie = "3.6.1"
rhea-trace = "2.0.3-rc02"

[libraries]
kotlin-stdlib-jdk7 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-navigation-fragment-base = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigaton" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigaton" }
androidx-navigation-ui-base = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigaton" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigaton" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
rhea-trace-core = { group = "com.bytedance.btrace", name = "rhea-core", version.ref = "rhea-trace" }

[plugins]
android-gradle-plugin = { id = "com.android.tools.build:gradle", version.ref = "android-plugin" }
kotlin-gradle-plugin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
navigation-safe-args-gradle-plugin = { id = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigaton" }
btrace-gradle-plugin = { id = "com.bytedance.btrace:rhea-gradle-plugin", version.ref = "rhea-trace" }
