{
  "formatVersion": "1.1",
  "component": {
    "group": "com.demo",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 13154,
          "sha512": "211b8059c740a9e618430a34838cf12fe639b9c32c629ec6313f55f2c48e937295dde31c70805815d6c04db88759ad10cc28e1012d286532d9090b56a658499b",
          "sha256": "72cc6c24c21b16c16552792211bb7ce36cf4e8f09cd321044c4f7ae1af0a5244",
          "sha1": "ea145e9aecfae1d8cf5c309b4b86bec413d4b0b6",
          "md5": "bbb4db049411dbd6418583248ea344c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 13154,
          "sha512": "211b8059c740a9e618430a34838cf12fe639b9c32c629ec6313f55f2c48e937295dde31c70805815d6c04db88759ad10cc28e1012d286532d9090b56a658499b",
          "sha256": "72cc6c24c21b16c16552792211bb7ce36cf4e8f09cd321044c4f7ae1af0a5244",
          "sha1": "ea145e9aecfae1d8cf5c309b4b86bec413d4b0b6",
          "md5": "bbb4db049411dbd6418583248ea344c0"
        }
      ]
    }
  ]
}
