{
  "formatVersion": "1.1",
  "component": {
    "group": "com.demo",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12950,
          "sha512": "9473c74cab0efcbd6ae96efe6cc85c38112c43c0c26e3d160e33cb7b0da763cd463ba078d643b69bd238cceeb51c384887025db6609a6eef8945cc2194b65acf",
          "sha256": "ef60aead91c5d70245d278467deef8634d9ed691d1ecb47e94bd75e570275e1c",
          "sha1": "ae0c8fdc570eaf291628c4b22166aa46a93192a8",
          "md5": "4d4afe429a750957a19315e983b443b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12950,
          "sha512": "9473c74cab0efcbd6ae96efe6cc85c38112c43c0c26e3d160e33cb7b0da763cd463ba078d643b69bd238cceeb51c384887025db6609a6eef8945cc2194b65acf",
          "sha256": "ef60aead91c5d70245d278467deef8634d9ed691d1ecb47e94bd75e570275e1c",
          "sha1": "ae0c8fdc570eaf291628c4b22166aa46a93192a8",
          "md5": "4d4afe429a750957a19315e983b443b7"
        }
      ]
    }
  ]
}
